"""init

Revision ID: 3aec10e859c6
Revises: 
Create Date: 2023-08-23 07:19:19.396697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3aec10e859c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('user_name', sa.Text(), nullable=True),
                    sa.Column('first_name', sa.Text(), nullable=True),
                    sa.Column('second_name', sa.Text(), nullable=True),
                    sa.Column('language_code', sa.Text(), nullable=True),
                    sa.Column('is_premium', sa.Boolean(), nullable=False),
                    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMINISTRATOR', name='role'), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id')
                    )
    op.create_table('category',
                    sa.Column('category_name', sa.Text(), nullable=False),
                    sa.Column('product_fk', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['product_fk'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('category_name', 'id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
