"""add_volume_in_product

Revision ID: 82683dcf45ea
Revises: b07b817fb6bd
Create Date: 2023-08-28 03:52:51.193873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82683dcf45ea'
down_revision: Union[str, None] = 'b07b817fb6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('volume', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'volume')
    # ### end Alembic commands ###
